import { MCP_TOOL_CATALOG } from './types.js';
import type {
  ChangeEntry,
  Credential,
  Item,
  Link,
  McpClient,
  McpConfig,
  McpLog,
  Note,
  Project,
  Release,
  TimeEntry,
} from './types.js';

/**
 * Örnek (kurgusal) veri. Yerel adaptör bunu ilk açılışta yükler,
 * `setup-appwrite` scripti de `--seed` ile aynı kayıtları backend'e yazar.
 * Projeler, alan adları, kullanıcı adları ve şifreler uydurmadır.
 */

const now = Date.now();
const ago = (ms: number) => new Date(now - ms).toISOString();
const MIN = 60_000;
const HOUR = 60 * MIN;
const DAY = 24 * HOUR;

export const seedProjects: Project[] = [
  {
    id: 'p_nova',
    slug: 'nova-okul',
    name: 'Nova Okul',
    subtitle: 'okul yönetim sistemi',
    status: 'gelistirme',
    progress: 68,
    version: 'v1.4.0',
    startDate: '2026-04-02T09:00:00.000Z',
    server: 'Docker · sunucu-1',
    domain: 'nova.example.com',
    sslStatus: 'geçerli',
    sslDays: 62,
    dns: 'Cloudflare',
    mcpEnabled: true,
    createdAt: ago(145 * DAY),
    updatedAt: ago(2 * HOUR),
  },
  {
    id: 'p_orbit',
    slug: 'orbit-kasa',
    name: 'Orbit Kasa',
    subtitle: 'e-ticaret yönetim paneli',
    status: 'canli',
    progress: 92,
    version: 'v0.8.2',
    startDate: '2026-01-15T09:00:00.000Z',
    server: 'Docker · sunucu-1',
    domain: 'orbit.example.com',
    sslStatus: 'geçerli',
    sslDays: 74,
    dns: 'Cloudflare',
    mcpEnabled: true,
    createdAt: ago(222 * DAY),
    updatedAt: ago(1 * DAY),
  },
  {
    id: 'p_atlas',
    slug: 'atlas-blog',
    name: 'Atlas Blog',
    subtitle: 'yayın platformu',
    status: 'canli',
    progress: 100,
    version: 'v2.1.0',
    startDate: '2025-11-02T09:00:00.000Z',
    server: 'Docker · sunucu-1',
    domain: 'atlas.example.com',
    sslStatus: 'geçerli',
    sslDays: 51,
    dns: 'Cloudflare',
    mcpEnabled: false,
    createdAt: ago(296 * DAY),
    updatedAt: ago(6 * DAY),
  },
  {
    id: 'p_pulse',
    slug: 'pulse-ik',
    name: 'Pulse İK',
    subtitle: 'iş ilanı portalı',
    status: 'test',
    progress: 81,
    version: 'v0.9.0',
    startDate: '2026-02-20T09:00:00.000Z',
    server: 'Docker · sunucu-1',
    domain: 'pulse.example.com',
    sslStatus: 'geçerli',
    sslDays: 38,
    dns: 'Cloudflare',
    mcpEnabled: false,
    createdAt: ago(186 * DAY),
    updatedAt: ago(3 * DAY),
  },
  {
    id: 'p_beacon',
    slug: 'beacon-sensor',
    name: 'Beacon Sensör',
    subtitle: 'IoT izleme paneli',
    status: 'beklemede',
    progress: 35,
    version: 'v0.3.1',
    startDate: '2026-05-11T09:00:00.000Z',
    server: 'Docker · sunucu-2',
    domain: 'beacon.example.com',
    sslStatus: 'geçerli',
    sslDays: 88,
    dns: 'Cloudflare',
    mcpEnabled: false,
    createdAt: ago(106 * DAY),
    updatedAt: ago(21 * DAY),
  },
  {
    id: 'p_lumen',
    slug: 'lumen-foto',
    name: 'Lumen Foto',
    subtitle: 'fotoğraf düzenleyici',
    status: 'teklif',
    progress: 12,
    version: 'v0.1.0',
    startDate: '2026-08-01T09:00:00.000Z',
    server: '—',
    domain: '—',
    sslStatus: '—',
    sslDays: null,
    dns: '—',
    mcpEnabled: false,
    createdAt: ago(24 * DAY),
    updatedAt: ago(9 * DAY),
  },
];

export const seedItems: Item[] = [
  {
    id: 'i_nova_1',
    projectId: 'p_nova',
    refNo: 131,
    type: 'bug',
    title: 'Öğrenci kaydında kimlik no doğrulama hatası',
    description: '11 haneli numarada bile "geçersiz" diyor, sadece Safari\'de',
    priority: 'kritik',
    status: 'open',
    reporter: 'Okul müdürü',
    tag: 'frontend',
    createdAt: ago(2 * HOUR),
    doneAt: null,
    releaseVersion: null,
  },
  {
    id: 'i_nova_2',
    projectId: 'p_nova',
    refNo: 130,
    type: 'bug',
    title: 'Rapor ekranı mobilde taşıyor',
    description: "Tablo yatay kayması yok, 390px'te bozuluyor",
    priority: 'orta',
    status: 'open',
    reporter: 'Yönetici',
    tag: 'css',
    createdAt: ago(1 * DAY),
    doneAt: null,
    releaseVersion: null,
  },
  {
    id: 'i_nova_3',
    projectId: 'p_nova',
    refNo: 129,
    type: 'bug',
    title: 'Devamsızlık bildirimi iki kere gidiyor',
    description: "Cron iki instance'ta da çalışıyor olabilir",
    priority: 'yuksek',
    status: 'open',
    reporter: 'Veli (WhatsApp)',
    tag: 'backend',
    createdAt: ago(2 * DAY),
    doneAt: null,
    releaseVersion: null,
  },
  {
    id: 'i_nova_4',
    projectId: 'p_nova',
    refNo: 127,
    type: 'bug',
    title: 'Not girişinde virgüllü değer kaydolmuyor',
    description: '',
    priority: 'orta',
    status: 'open',
    reporter: 'Öğretmen',
    tag: 'validation',
    createdAt: ago(4 * DAY),
    doneAt: null,
    releaseVersion: null,
  },
  {
    id: 'i_nova_5',
    projectId: 'p_nova',
    refNo: 125,
    type: 'task',
    title: 'Excel dışa aktarma eklenecek',
    description: 'Dönem sonu raporu Excel olarak da inebilsin',
    priority: 'istek',
    status: 'open',
    reporter: 'Okul müdürü',
    tag: 'rapor',
    createdAt: ago(3 * DAY),
    doneAt: null,
    releaseVersion: null,
  },
  {
    id: 'i_nova_6',
    projectId: 'p_nova',
    refNo: 124,
    type: 'task',
    title: 'Yetki grupları ekranı',
    description: '',
    priority: 'istek',
    status: 'open',
    reporter: 'Yönetici',
    tag: 'backend',
    createdAt: ago(5 * DAY),
    doneAt: null,
    releaseVersion: null,
  },
  {
    id: 'i_nova_7',
    projectId: 'p_nova',
    refNo: 128,
    type: 'bug',
    title: 'Giriş ekranında yanlış şifre mesajı çıkmıyor',
    description: '',
    priority: 'dusuk',
    status: 'done',
    reporter: 'Yönetici',
    tag: 'auth',
    createdAt: ago(6 * DAY),
    doneAt: ago(2 * HOUR),
    releaseVersion: 'v1.4.0',
  },
  {
    id: 'i_nova_8',
    projectId: 'p_nova',
    refNo: 126,
    type: 'bug',
    title: 'Ders programı kaydederken 500 dönüyor',
    description: '',
    priority: 'yuksek',
    status: 'done',
    reporter: 'Okul müdürü',
    tag: 'backend',
    createdAt: ago(7 * DAY),
    doneAt: ago(3 * HOUR),
    releaseVersion: 'v1.4.0',
  },
  {
    id: 'i_nova_9',
    projectId: 'p_nova',
    refNo: 121,
    type: 'task',
    title: 'Veli paneline devamsızlık özeti eklendi',
    description: '',
    priority: 'istek',
    status: 'done',
    reporter: 'Yönetici',
    tag: 'veli',
    createdAt: ago(12 * DAY),
    doneAt: ago(4 * DAY),
    releaseVersion: 'v1.4.0',
  },
  {
    id: 'i_nova_10',
    projectId: 'p_nova',
    refNo: 119,
    type: 'task',
    title: 'Rapor sorguları 2.4s → 0.6s',
    description: 'Index eklendi, N+1 kaldırıldı',
    priority: 'orta',
    status: 'done',
    reporter: 'Yönetici',
    tag: 'performans',
    createdAt: ago(16 * DAY),
    doneAt: ago(5 * DAY),
    releaseVersion: 'v1.4.0',
  },
  {
    id: 'i_orbit_1',
    projectId: 'p_orbit',
    refNo: 42,
    type: 'bug',
    title: 'Büyük katalog yüklerken sekme donuyor',
    description: '10 binden fazla ürün olunca ana iş parçacığı kilitleniyor',
    priority: 'yuksek',
    status: 'open',
    reporter: 'Kullanıcı (mail)',
    tag: 'performans',
    createdAt: ago(3 * DAY),
    doneAt: null,
    releaseVersion: null,
  },
  {
    id: 'i_orbit_2',
    projectId: 'p_orbit',
    refNo: 41,
    type: 'bug',
    title: 'Kargo etiketinde Türkçe karakter sorunu',
    description: '',
    priority: 'orta',
    status: 'open',
    reporter: 'Yönetici',
    tag: 'kargo',
    createdAt: ago(8 * DAY),
    doneAt: null,
    releaseVersion: null,
  },
  {
    id: 'i_pulse_1',
    projectId: 'p_pulse',
    refNo: 63,
    type: 'bug',
    title: 'İlan arama filtresi şehir seçince boş dönüyor',
    description: '',
    priority: 'yuksek',
    status: 'open',
    reporter: 'Test kullanıcısı',
    tag: 'arama',
    createdAt: ago(2 * DAY),
    doneAt: null,
    releaseVersion: null,
  },
  {
    id: 'i_pulse_2',
    projectId: 'p_pulse',
    refNo: 62,
    type: 'bug',
    title: 'İşveren panelinde logo yüklenmiyor',
    description: '',
    priority: 'orta',
    status: 'open',
    reporter: 'Yönetici',
    tag: 'upload',
    createdAt: ago(5 * DAY),
    doneAt: null,
    releaseVersion: null,
  },
  {
    id: 'i_pulse_3',
    projectId: 'p_pulse',
    refNo: 61,
    type: 'bug',
    title: 'CV indirme linki 404',
    description: '',
    priority: 'kritik',
    status: 'open',
    reporter: 'İşveren',
    tag: 'backend',
    createdAt: ago(1 * DAY),
    doneAt: null,
    releaseVersion: null,
  },
  {
    id: 'i_pulse_4',
    projectId: 'p_pulse',
    refNo: 60,
    type: 'bug',
    title: 'E-posta doğrulama maili spam\'e düşüyor',
    description: 'SPF/DKIM kayıtları eksik olabilir',
    priority: 'orta',
    status: 'open',
    reporter: 'Yönetici',
    tag: 'mail',
    createdAt: ago(9 * DAY),
    doneAt: null,
    releaseVersion: null,
  },
  {
    id: 'i_atlas_1',
    projectId: 'p_atlas',
    refNo: 24,
    type: 'bug',
    title: 'Yazılarda kod bloğu taşıyor',
    description: '',
    priority: 'dusuk',
    status: 'open',
    reporter: 'Yönetici',
    tag: 'css',
    createdAt: ago(11 * DAY),
    doneAt: null,
    releaseVersion: null,
  },
  {
    id: 'i_beacon_1',
    projectId: 'p_beacon',
    refNo: 18,
    type: 'task',
    title: 'Müşteri onayı bekleniyor — sözleşme revizyonu',
    description: '',
    priority: 'istek',
    status: 'open',
    reporter: 'Yönetici',
    tag: 'süreç',
    createdAt: ago(21 * DAY),
    doneAt: null,
    releaseVersion: null,
  },
];

export const seedNotes: Note[] = [
  {
    id: 'n_1',
    projectId: 'p_nova',
    body: 'Müşteri, dönem sonu raporunun PDF olarak da inebilmesini istedi. Şablonu okul logolu olacak.',
    context: 'telefon görüşmesi',
    importance: 'normal',
    createdAt: '2026-08-18T11:20:00.000Z',
  },
  {
    id: 'n_2',
    projectId: 'p_nova',
    body: "Cron 03:00'te yedek alıyor, nesne depolamaya gidiyor. Retention 14 gün.",
    context: 'teknik',
    importance: 'normal',
    createdAt: '2026-08-11T08:05:00.000Z',
  },
  {
    id: 'n_3',
    projectId: 'p_nova',
    body: "Kimlik no doğrulaması Safari'de regex lookbehind'ı desteklemiyor — polyfill ya da manuel kontrol gerekiyor.",
    context: 'yapay zeka · MCP',
    importance: 'cok_onemli',
    createdAt: ago(1 * DAY),
  },
  {
    id: 'n_4',
    projectId: 'p_nova',
    body: 'Eylül ayında dış entegrasyon tokenı yenilenecek, 11 aydır aynı.',
    context: 'hatırlatma',
    importance: 'cok_onemli',
    createdAt: ago(9 * DAY),
  },
  {
    id: 'n_5',
    projectId: 'p_pulse',
    body: 'Yeni ilan sayfası tasarımı onaylandı, geliştirmeye eylül başında başlanacak.',
    context: 'toplantı',
    importance: 'normal',
    createdAt: ago(4 * DAY),
  },
  {
    id: 'n_6',
    projectId: 'p_atlas',
    body: 'Ana sayfadaki proje listesi otomatik bu panelden çekilecek.',
    context: 'fikir',
    importance: 'az_onemli',
    createdAt: ago(13 * DAY),
  },
];

export const seedReleases: Release[] = [
  {
    id: 'r_nova_141',
    projectId: 'p_nova',
    version: 'v1.4.1',
    date: new Date(now).toISOString(),
    status: 'draft',
    createdAt: ago(2 * HOUR),
  },
  {
    id: 'r_nova_140',
    projectId: 'p_nova',
    version: 'v1.4.0',
    date: '2026-08-25T09:00:00.000Z',
    status: 'released',
    createdAt: '2026-08-25T09:00:00.000Z',
  },
  {
    id: 'r_nova_132',
    projectId: 'p_nova',
    version: 'v1.3.2',
    date: '2026-08-12T09:00:00.000Z',
    status: 'released',
    createdAt: '2026-08-12T09:00:00.000Z',
  },
  {
    id: 'r_nova_130',
    projectId: 'p_nova',
    version: 'v1.3.0',
    date: '2026-07-29T09:00:00.000Z',
    status: 'released',
    createdAt: '2026-07-29T09:00:00.000Z',
  },
  {
    id: 'r_orbit_082',
    projectId: 'p_orbit',
    version: 'v0.8.2',
    date: ago(1 * DAY),
    status: 'released',
    createdAt: ago(1 * DAY),
  },
  {
    id: 'r_pulse_090',
    projectId: 'p_pulse',
    version: 'v0.9.0',
    date: ago(3 * DAY),
    status: 'released',
    createdAt: ago(3 * DAY),
  },
  {
    id: 'r_atlas_210',
    projectId: 'p_atlas',
    version: 'v2.1.0',
    date: ago(6 * DAY),
    status: 'released',
    createdAt: ago(6 * DAY),
  },
];

export const seedChangeEntries: ChangeEntry[] = [
  {
    id: 'c_1',
    projectId: 'p_nova',
    releaseId: 'r_nova_141',
    kind: 'fix',
    text: 'Not girişinde virgüllü değer düzeltmesi',
    refNo: null,
    createdAt: ago(2 * HOUR),
  },
  {
    id: 'c_2',
    projectId: 'p_nova',
    releaseId: 'r_nova_141',
    kind: 'improve',
    text: 'Logo güncellemesi',
    refNo: null,
    createdAt: ago(2 * HOUR),
  },
  {
    id: 'c_3',
    projectId: 'p_nova',
    releaseId: 'r_nova_140',
    kind: 'fix',
    text: 'Giriş ekranında yanlış şifre mesajı görünmüyordu',
    refNo: 128,
    createdAt: '2026-08-25T09:00:00.000Z',
  },
  {
    id: 'c_4',
    projectId: 'p_nova',
    releaseId: 'r_nova_140',
    kind: 'fix',
    text: 'Ders programı kaydında 500 hatası',
    refNo: 126,
    createdAt: '2026-08-25T09:00:00.000Z',
  },
  {
    id: 'c_5',
    projectId: 'p_nova',
    releaseId: 'r_nova_140',
    kind: 'new',
    text: 'Veli paneline devamsızlık özeti eklendi',
    refNo: 121,
    createdAt: '2026-08-25T09:00:00.000Z',
  },
  {
    id: 'c_6',
    projectId: 'p_nova',
    releaseId: 'r_nova_140',
    kind: 'improve',
    text: 'Rapor sorguları 2.4s → 0.6s',
    refNo: 119,
    createdAt: '2026-08-25T09:00:00.000Z',
  },
  {
    id: 'c_7',
    projectId: 'p_nova',
    releaseId: 'r_nova_132',
    kind: 'fix',
    text: 'Fotoğraf yüklemede 5MB üstü dosyalar sessizce düşüyordu',
    refNo: 114,
    createdAt: '2026-08-12T09:00:00.000Z',
  },
  {
    id: 'c_8',
    projectId: 'p_nova',
    releaseId: 'r_nova_132',
    kind: 'improve',
    text: 'Yedekler nesne depolamaya taşındı, retention 14 gün',
    refNo: 110,
    createdAt: '2026-08-12T09:00:00.000Z',
  },
  {
    id: 'c_9',
    projectId: 'p_nova',
    releaseId: 'r_nova_130',
    kind: 'new',
    text: 'Ders programı modülü',
    refNo: 98,
    createdAt: '2026-07-29T09:00:00.000Z',
  },
  {
    id: 'c_10',
    projectId: 'p_nova',
    releaseId: 'r_nova_130',
    kind: 'removed',
    text: 'Eski SMS sağlayıcısı desteği',
    refNo: 95,
    createdAt: '2026-07-29T09:00:00.000Z',
  },
  {
    id: 'c_11',
    projectId: 'p_orbit',
    releaseId: 'r_orbit_082',
    kind: 'fix',
    text: 'CSV içe aktarma boş satırlarda çöküyordu',
    refNo: 39,
    createdAt: ago(1 * DAY),
  },
  {
    id: 'c_12',
    projectId: 'p_pulse',
    releaseId: 'r_pulse_090',
    kind: 'new',
    text: 'İşveren paneli ilk sürüm',
    refNo: 55,
    createdAt: ago(3 * DAY),
  },
  {
    id: 'c_13',
    projectId: 'p_atlas',
    releaseId: 'r_atlas_210',
    kind: 'improve',
    text: 'Yazı sayfaları statik üretime geçti',
    refNo: 21,
    createdAt: ago(6 * DAY),
  },
];

export const seedCredentials: Credential[] = [
  {
    id: 'cr_1',
    projectId: 'p_nova',
    service: 'Deploy paneli',
    username: 'admin',
    secret: 'Xk4!pT9wLq',
    twoFactor: 'active',
    color: '',
    updatedAt: ago(14 * DAY),
  },
  {
    id: 'cr_2',
    projectId: 'p_nova',
    service: 'Appwrite konsolu',
    username: 'admin@example.com',
    secret: 'Qa!2rN8vZm4c',
    twoFactor: 'active',
    color: '',
    updatedAt: ago(61 * DAY),
  },
  {
    id: 'cr_3',
    projectId: 'p_nova',
    service: 'Cloudflare',
    username: 'admin@example.com',
    secret: 'Hf#6bW3yKp9',
    twoFactor: 'active',
    color: '',
    updatedAt: ago(31 * DAY),
  },
  {
    id: 'cr_4',
    projectId: 'p_nova',
    service: 'Postgres · nova_prod',
    username: 'nova_app',
    secret: 'pg_4Lm7!Vd2Xs',
    twoFactor: 'none',
    color: '',
    updatedAt: ago(122 * DAY),
  },
  {
    id: 'cr_5',
    projectId: 'p_nova',
    service: 'SMTP · bildirim',
    username: 'no-reply@nova.example.com',
    secret: 'sm3$Tk8Yq1',
    twoFactor: 'none',
    color: '',
    updatedAt: ago(213 * DAY),
  },
  {
    id: 'cr_6',
    projectId: 'p_nova',
    service: 'Dış entegrasyon API',
    username: 'token',
    secret: 'ext_live_5a27d9c1e4',
    twoFactor: 'expiring',
    color: '',
    updatedAt: ago(334 * DAY),
  },
  {
    id: 'cr_7',
    projectId: 'p_orbit',
    service: 'Nesne depolama',
    username: 'orbit-access-key',
    secret: 's3_Vb52!nJ8k',
    twoFactor: 'none',
    color: '',
    updatedAt: ago(45 * DAY),
  },
  {
    id: 'cr_8',
    projectId: 'p_pulse',
    service: 'Appwrite konsolu',
    username: 'admin@example.com',
    secret: 'Qa!2rN8vZm4c',
    twoFactor: 'active',
    color: '',
    updatedAt: ago(61 * DAY),
  },
];

export const seedLinks: Link[] = [
  { id: 'l_1', projectId: 'p_nova', label: 'Canlı site', url: 'https://nova.example.com', kind: 'live' },
  {
    id: 'l_2',
    projectId: 'p_nova',
    label: 'Git deposu',
    url: 'https://github.com/example/nova-okul',
    kind: 'repo',
  },
  {
    id: 'l_3',
    projectId: 'p_nova',
    label: 'Deploy paneli',
    url: 'https://deploy.example.com',
    kind: 'panel',
  },
  {
    id: 'l_4',
    projectId: 'p_nova',
    label: 'Appwrite konsolu',
    url: 'https://appwrite.example.com',
    kind: 'console',
  },
  { id: 'l_5', projectId: 'p_orbit', label: 'Canlı site', url: 'https://orbit.example.com', kind: 'live' },
  {
    id: 'l_6',
    projectId: 'p_orbit',
    label: 'Git deposu',
    url: 'https://github.com/example/orbit-kasa',
    kind: 'repo',
  },
  { id: 'l_7', projectId: 'p_pulse', label: 'Canlı site', url: 'https://pulse.example.com', kind: 'live' },
  {
    id: 'l_8',
    projectId: 'p_atlas',
    label: 'Canlı site',
    url: 'https://atlas.example.com',
    kind: 'live',
  },
];

export const seedTimeEntries: TimeEntry[] = [
  {
    id: 't_1',
    projectId: 'p_nova',
    itemId: 'i_nova_1',
    startedAt: ago(3 * HOUR),
    endedAt: ago(1 * HOUR),
    minutes: 120,
    note: 'Kimlik no doğrulama araştırması',
  },
  {
    id: 't_2',
    projectId: 'p_nova',
    itemId: 'i_nova_8',
    startedAt: ago(1 * DAY),
    endedAt: ago(1 * DAY - 4 * HOUR),
    minutes: 240,
    note: 'Ders programı 500 hatası',
  },
  {
    id: 't_3',
    projectId: 'p_nova',
    itemId: null,
    startedAt: ago(3 * DAY),
    endedAt: ago(3 * DAY - 5 * HOUR),
    minutes: 300,
    note: 'Rapor modülü',
  },
  {
    id: 't_4',
    projectId: 'p_nova',
    itemId: null,
    startedAt: ago(40 * DAY),
    endedAt: ago(40 * DAY - 20 * HOUR),
    minutes: 1270,
    note: 'İlk kurulum ve modüller',
  },
  {
    id: 't_5',
    projectId: 'p_orbit',
    itemId: null,
    startedAt: ago(30 * DAY),
    endedAt: ago(30 * DAY - 10 * HOUR),
    minutes: 3665,
    note: 'Toplam geliştirme',
  },
  {
    id: 't_6',
    projectId: 'p_atlas',
    itemId: null,
    startedAt: ago(60 * DAY),
    endedAt: ago(60 * DAY - 6 * HOUR),
    minutes: 750,
    note: 'Site yenileme',
  },
  {
    id: 't_7',
    projectId: 'p_pulse',
    itemId: null,
    startedAt: ago(2 * DAY),
    endedAt: ago(2 * DAY - 4 * HOUR),
    minutes: 2655,
    note: 'Portal geliştirme',
  },
  {
    id: 't_8',
    projectId: 'p_beacon',
    itemId: null,
    startedAt: ago(25 * DAY),
    endedAt: ago(25 * DAY - 3 * HOUR),
    minutes: 480,
    note: 'Sensör paneli prototipi',
  },
];

const allTools = MCP_TOOL_CATALOG.filter((tool) => tool.defaultEnabled).map((tool) => tool.name);

export const seedMcpConfigs: McpConfig[] = [
  {
    id: 'm_nova',
    projectId: 'p_nova',
    enabled: true,
    token: 'mcp_nova_3f9a12c7d84be05a',
    enabledTools: allTools,
    autoApply: true,
    createdAt: ago(30 * DAY),
  },
  {
    id: 'm_orbit',
    projectId: 'p_orbit',
    enabled: true,
    token: 'mcp_orbit_8c2e51ab07fd3946',
    enabledTools: allTools,
    autoApply: false,
    createdAt: ago(20 * DAY),
  },
];

export const seedMcpClients: McpClient[] = [
  {
    id: 'mc_1',
    projectId: 'p_nova',
    name: 'Masaüstü istemci',
    mode: 'readwrite',
    lastSeenAt: ago(20_000),
  },
  {
    id: 'mc_2',
    projectId: 'p_nova',
    name: 'Terminal istemcisi',
    mode: 'readwrite',
    lastSeenAt: ago(6 * MIN),
  },
  {
    id: 'mc_3',
    projectId: 'p_nova',
    name: 'Mobil istemci',
    mode: 'read',
    lastSeenAt: ago(2 * DAY),
  },
];

export const seedMcpLogs: McpLog[] = [
  {
    id: 'ml_1',
    projectId: 'p_nova',
    tool: 'update_status',
    summary: '#126 "Ders programı kaydında 500" → yapıldı, v1.4.0 changelog\'una eklendi',
    client: 'Masaüstü istemci',
    createdAt: ago(4 * MIN),
  },
  {
    id: 'ml_2',
    projectId: 'p_nova',
    tool: 'list_bugs',
    summary: '6 açık hata okundu · filtre: öncelik ≥ yüksek',
    client: 'Masaüstü istemci',
    createdAt: ago(21 * MIN),
  },
  {
    id: 'ml_3',
    projectId: 'p_nova',
    tool: 'add_note',
    summary: '"Kimlik no doğrulaması Safari\'de regex lookbehind\'ı desteklemiyor" notu eklendi',
    client: 'Terminal istemcisi',
    createdAt: ago(1 * DAY),
  },
  {
    id: 'ml_4',
    projectId: 'p_nova',
    tool: 'add_bug',
    summary: '"Devamsızlık bildirimi iki kere gidiyor" kaydı açıldı · yüksek',
    client: 'Masaüstü istemci',
    createdAt: ago(2 * DAY),
  },
];

export const seedData = {
  projects: seedProjects,
  items: seedItems,
  notes: seedNotes,
  releases: seedReleases,
  changeEntries: seedChangeEntries,
  credentials: seedCredentials,
  links: seedLinks,
  timeEntries: seedTimeEntries,
  mcpConfigs: seedMcpConfigs,
  mcpClients: seedMcpClients,
  mcpLogs: seedMcpLogs,
};
